pipeline {
    agent any

    tools {
        maven 'MAVEN_HOME' // This must match the name you gave in Global Tool Configuration
    }

    stages {
        stage('Checkout') {
            steps {
                echo 'Pulling code from GitHub...'
            }
        }

        stage('Build') {
            steps {
                sh 'mvn clean package -DskipTests'
            }
        }

        stage('SonarQube Analysis') {
            steps {
                // This 'SonarQube-Server' must match the name in System Configuration
                withSonarQubeEnv('SonarQube-Server') {
                    sh 'mvn sonar:sonar'
                }
            }
        }
    }
}
