pipeline {
    agent any

    tools {
        maven 'MAVEN_HOME' // This must match the name you gave in Global Tool Configuration
    }

    stages {
        stage('Checkout') {
            steps {
                echo 'Pulling code from GitHub...'
            }
        }

        stage('Build') {
    steps {
        // We 'dir' into the folder so the shell runs inside the app directory
        dir('java-maven-sonar-argocd-helm-k8s/spring-boot-app') {
            sh 'mvn clean package -DskipTests'
        }
    }
}

stage('SonarQube Analysis') {
    steps {
        dir('java-maven-sonar-argocd-helm-k8s/spring-boot-app') {
            withSonarQubeEnv('SonarQube-Server') {
                sh 'mvn sonar:sonar'
            }
        }
    }
}
    }
}
